# Generated by Django 5.2 on 2025-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Název')),
                ('trailer', models.CharField(max_length=1500, verbose_name='Upoutávka')),
                ('text', models.TextField(verbose_name='Text přízpěvku')),
                ('author', models.CharField(max_length=100, verbose_name='Jméno autora')),
                ('visible', models.BooleanField(default=True, verbose_name='Viditelný')),
                ('issue_date', models.DateField(verbose_name='Čas vidání')),
                ('reading_time', models.PositiveIntegerField(verbose_name='Čas čtení')),
            ],
        ),
    ]
