# Generated by Django 5.2 on 2025-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog_app/cover_images', verbose_name='Obrázek'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='issue_date',
            field=models.DateTimeField(verbose_name='Čas vydání'),
        ),
    ]
