# Generated by Django 4.2.22 on 2025-06-16 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempts',
            field=models.PositiveIntegerField(default=3, verbose_name='Počet pokusů'),
        ),
        migrations.AddField(
            model_name='profile',
            name='earn',
            field=models.IntegerField(default=1, verbose_name='Výdělek'),
        ),
        migrations.AddField(
            model_name='profile',
            name='golden_tickets',
            field=models.IntegerField(default=0, verbose_name='Tikety'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 6, 16), verbose_name='Datum Poslední aktivity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=1000, verbose_name='Peníze'),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Číslo aktuální místnosti'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tickets_per_day',
            field=models.PositiveIntegerField(default=0, verbose_name='Počet nakoupených tiketů'),
        ),
    ]
