# Generated by Django 5.2 on 2025-06-25 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_attempts_profile_earn_profile_golden_tickets_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kódu')),
                ('add_points', models.IntegerField(default=0, verbose_name='Kolik přidá bodů')),
                ('add_modey', models.IntegerField(default=0, verbose_name='Kolik přidá peněz')),
                ('add_golden_tickets', models.IntegerField(default=0, verbose_name='kolik přidá tiketů')),
                ('add_eaern', models.IntegerField(default=0, verbose_name='Kolik přidá výdělek')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Zpráva co kód vypíše')),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
