# Generated by Django 5.2 on 2025-06-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_add_modey_codes_add_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='add_eaern',
            new_name='add_aern',
        ),
    ]
