# Generated by Django 5.2 on 2025-06-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_add_eaern_codes_add_aern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='add_aern',
            new_name='add_earn',
        ),
    ]
