# Generated by Django 5.2 on 2025-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_add_aern_codes_add_earn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, verbose_name='Číslo dne')),
                ('golden_ticket_cost', models.PositiveIntegerField(default=0, verbose_name='Cena tiketu')),
                ('type_of_quiz', models.CharField(max_length=100, verbose_name='Typ kvízu')),
                ('secret_text', models.CharField(max_length=100, verbose_name='Tajný text')),
            ],
        ),
    ]
