# Generated by Django 5.2 on 2025-06-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'verbose_name_plural': 'Codes'},
        ),
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name_plural': 'Days'},
        ),
    ]
