# Generated by Django 5.2 on 2025-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_codes_options_alter_days_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.CharField(max_length=250, verbose_name='Text otázky')),
                ('choise_1', models.CharField(max_length=100, verbose_name='Odpověď č.1')),
                ('choise_2', models.CharField(max_length=100, verbose_name='Odpověď č.2')),
                ('choise_3', models.CharField(max_length=100, verbose_name='Odpověď č.3')),
                ('answer_quiz', models.CharField(max_length=100, verbose_name='právná odpověď')),
            ],
        ),
        migrations.AlterField(
            model_name='days',
            name='day_number',
            field=models.PositiveIntegerField(verbose_name='Číslo dne'),
        ),
        migrations.AlterField(
            model_name='days',
            name='golden_ticket_cost',
            field=models.PositiveIntegerField(verbose_name='Cena tiketu'),
        ),
    ]
