# Generated by Django 5.2 on 2025-06-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_quiz_alter_days_day_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='day_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Číslo dne'),
            preserve_default=False,
        ),
    ]
