# Generated by Django 5.2 on 2025-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_quiz_day_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_with_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Číslo dne')),
                ('text_question', models.CharField(max_length=250, verbose_name='Text otázky')),
                ('user_answer', models.TextField(verbose_name='Odpověd uživatele')),
            ],
        ),
    ]
