# Generated by Django 5.2 on 2025-06-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_small_answer_alter_work_with_text_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Číslo dne')),
                ('text', models.TextField(verbose_name='Text příběhu')),
                ('user_answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Odpověď uživatele')),
                ('answer_quiz', models.CharField(max_length=100, verbose_name='správná odpověď')),
            ],
        ),
        migrations.AddField(
            model_name='small_answer',
            name='answer_quiz',
            field=models.CharField(default='pokus', max_length=100, verbose_name='správná odpověď'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answer_quiz',
            field=models.CharField(max_length=100, verbose_name='správná odpověď'),
        ),
    ]
