# Generated by Django 5.2 on 2025-06-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_story_small_answer_answer_quiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='text',
            new_name='text_question',
        ),
    ]
