# Generated by Django 5.2 on 2025-06-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_text_story_text_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Číslo dne')),
                ('room_number', models.PositiveIntegerField(verbose_name='Číslo místnosti')),
                ('question', models.CharField(max_length=250, verbose_name='Otázka')),
                ('user_answer', models.CharField(max_length=100, verbose_name='Odpověď uživatele na otázku')),
                ('right_answer', models.CharField(max_length=100, verbose_name='Správná odpověď na otázku')),
                ('add_points', models.IntegerField(default=0, verbose_name='Kolik přidá bodů')),
                ('add_money', models.IntegerField(default=0, verbose_name='Kolik přidá peněz')),
                ('add_golden_tickets', models.IntegerField(default=0, verbose_name='kolik přidá tiketů')),
                ('add_earn', models.IntegerField(default=0, verbose_name='Kolik přidá výdělek')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Zpráva co kód vypíše')),
                ('attempts', models.PositiveIntegerField(default=3, verbose_name='Počet pokusů')),
            ],
        ),
    ]
