# Generated by Django 5.2 on 2025-06-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='room_index',
            field=models.PositiveIntegerField(default=1, verbose_name='Číslo aktuální místnosti'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Odpověď uživatele na otázku'),
        ),
    ]
