# Generated by Django 5.2 on 2025-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_quiz_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_quiz',
            field=models.BooleanField(default=False, verbose_name='Má kvíz'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Obsah profilu'),
        ),
    ]
