# Generated by Django 5.2 on 2025-06-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_profile_has_quiz_alter_profile_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='small_answer',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='work_with_text',
            name='user_answer',
        ),
    ]
