# Generated by Django 4.2.22 on 2025-06-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_recipient_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sendet_by',
            field=models.CharField(default='vojta', max_length=100),
            preserve_default=False,
        ),
    ]
