# Generated by Django 4.2.22 on 2025-06-16 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_product_cost_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=1000, verbose_name='Peníze')),
                ('earn', models.IntegerField(default=1, verbose_name='Výdělek')),
                ('golden_tickets', models.IntegerField(default=0, verbose_name='Tikety')),
                ('attempts', models.PositiveIntegerField(default=3, verbose_name='Počet pokusů')),
                ('last_activity_date', models.DateField(auto_now_add=True, verbose_name='Datum Poslední aktivity')),
                ('room_index', models.PositiveIntegerField(default=0, verbose_name='Číslo aktuální místnosti')),
                ('tickets_per_day', models.PositiveIntegerField(default=0, verbose_name='Počet nakoupených tiketů')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
