# Generated by Django 4.2.22 on 2025-06-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_playerstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
