# Generated by Django 4.2.22 on 2025-06-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgrade',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Popis'),
        ),
    ]
